### ISSUE TITLE
Crash on any click

### ISSUE THREAD

**Issue by nidico** [JOSM/JOSM-areaselector#16]
Trying to make use of the areaselector fails for me with the backtrace below.

This has also been [reported in the OSM forum](http://forum.openstreetmap.org/viewtopic.php?id=29721).

> JOSM: Version 8159
> Java: Version 1.8.0_40
> Areaselector: Version 1423773025

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at boofcv.alg.feature.shapes.SplitMergeLineFitLoop.checkSplit(SplitMergeLineFitLoop.java:216)
	at boofcv.alg.feature.shapes.SplitMergeLineFitLoop.splitSegments(SplitMergeLineFitLoop.java:205)
	at boofcv.alg.feature.shapes.SplitMergeLineFitLoop.process(SplitMergeLineFitLoop.java:77)
	at boofcv.alg.feature.shapes.ShapeFittingOps.fitPolygon(ShapeFittingOps.java:71)
	at org.openstreetmap.josm.plugins.areaselector.ImageAnalyzer.detectArea(ImageAnalyzer.java:791)
	at org.openstreetmap.josm.plugins.areaselector.ImageAnalyzer.getArea(ImageAnalyzer.java:256)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction.createArea(AreaSelectorAction.java:166)
	at org.openstreetmap.josm.plugins.areaselector.AreaSelectorAction.mouseClicked(AreaSelectorAction.java:121)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by r00tat** [comment]
I was unable to reproduce that issue. 

I tried with Java 1.7.0_71 and Java 1.8.0_45, JOSM 8159 and JSOM 8212. 

What background image did you use?
Could you let me know the coordinates?

**Comment by nidico** [comment]
This is indeed fixed in the current version.

**Comment by r00tat** [comment]
thanks for your feedback!
